### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception

### ISSUE THREAD

**Issue by morskoyzmey** [josxha/flutter_map_cache#6]
Some map providers give me such an exception, while the images eventually load successfully.

Exception throws `(package:flutter_map_cache/src/cached_image_provider.dart:84:13)`

UPD. I logged `onReceiveProgress: (count, total)` event and it seems that `total` is -1 for some reason.

```E/flutter (21781): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/painting/image_stream.dart': Failed assertion: line 272 pos 15: 'expectedTotalBytes == null || expectedTotalBytes >= 0': is not true.
E/flutter (21781): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (21781): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (21781): #2      new ImageChunkEvent (package:flutter/src/painting/image_stream.dart:272:15)
E/flutter (21781): #3      CachedImageProvider._loadAsync.<anonymous closure> (package:flutter_map_cache/src/cached_image_provider.dart:84:13)
E/flutter (21781): #4      SyncTransformer.transformResponse.<anonymous closure> (package:dio/src/transformers/sync_transformer.dart:82:36)
E/flutter (21781): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (21781): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21781): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21781): #8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
E/flutter (21781): #9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
E/flutter (21781): #10     IOHttpClientAdapter._fetch.<anonymous closure> (package:dio/src/adapters/io_adapter.dart:242:18)
E/flutter (21781): #11     _HandlerEventSink.add (dart:async/stream_transformers.dart:209:17)
E/flutter (21781): #12     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
E/flutter (21781): #13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (21781): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21781): #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21781): #16     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (21781): #17     _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter (21781): #18     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (21781): #19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (21781): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21781): #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21781): #22     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (21781): #23     _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (21781): #24     _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (21781): #25     _HttpParser._doParse (dart:_http/http_parser.dart:829:28)
E/flutter (21781): #26     _HttpParser._parse (dart:_http/http_parser.dart:319:7)
E/flutter (21781): #27     _HttpParser._onData (dart:_http/http_parser.dart:873:5)
E/flutter (21781): #28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (21781): #29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21781): #30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21781): #31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (21781): #32     _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (21781): #33     _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (21781): #34     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
E/flutter (21781): #35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (21781): #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (21781): #37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (21781): #38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (21781): #39     _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (21781): #40     _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (21781): #41     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1114:19)
E/flutter (21781): #42     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (21781): #43     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (21781): #44     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (21781): #45     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)```

**Comment by josxha** [comment]
Thanks for opening an issue @morskoyzmey. I haven't experienced this behaviour before. Could you give some additional information and some code so I can try to reproduce this?

**Comment by josxha** [comment]
Closing this staled issue.
